{{- range $key, $value := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  namespace: default
spec:
  type: {{ $value.type }}
  ports:
    - port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      protocol: TCP
  selector:
    app: {{ $value.appName }}
---
{{- end}}
